# Generated by Django 5.1.7 on 2025-06-01 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "PATIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="patient_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                            ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                        ],
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Phone Number"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Emergency Contact Name",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Emergency Contact Phone",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Profile Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Profile Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Record Date and Time",
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Diagnosis")),
                ("symptoms", models.TextField(blank=True, verbose_name="Symptoms")),
                (
                    "treatment_plan",
                    models.TextField(blank=True, verbose_name="Treatment Plan"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Additional Notes (Medical Record)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Entry Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Entry Updated At"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["DOCTOR", "NURSE", "ADMIN"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_medical_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By (Staff)",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "ordering": ["-record_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-record_date"],
                        name="patients_me_patient_6c698d_idx",
                    ),
                    models.Index(
                        fields=["created_by", "record_date"],
                        name="patients_me_created_b549fd_idx",
                    ),
                ],
            },
        ),
    ]
