# Generated by Django 5.1.7 on 2025-06-01 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("GENERAL_CONSULTATION", "General Consultation"),
                            ("SPECIALIST_VISIT", "Specialist Visit"),
                            ("FOLLOW_UP", "Follow-up"),
                            ("TELEMEDICINE", "Telemedicine"),
                            ("PROCEDURE", "Procedure"),
                            ("CHECK_UP", "Check-up"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="GENERAL_CONSULTATION",
                        max_length=50,
                        verbose_name="Appointment Type",
                    ),
                ),
                (
                    "appointment_date_time",
                    models.DateTimeField(verbose_name="Appointment Date and Time"),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Estimated duration of the appointment in minutes.",
                        verbose_name="Estimated Duration (minutes)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED_BY_PATIENT", "Cancelled by Patient"),
                            ("CANCELLED_BY_STAFF", "Cancelled by Staff"),
                            ("COMPLETED", "Completed"),
                            ("NO_SHOW", "No Show"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=30,
                        verbose_name="Appointment Status",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Brief reason provided by the patient or scheduler for the visit.",
                        verbose_name="Reason for Appointment",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes by staff or additional details from patient during booking.",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "original_appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the original appointment if this is a rescheduled one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_to",
                        to="appointments.appointment",
                        verbose_name="Original Appointment (if rescheduled)",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who scheduled the appointment (e.g., patient, receptionist, admin).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Scheduled By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["appointment_date_time"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "appointment_date_time"],
                        name="appointment_doctor__6f5910_idx",
                    ),
                    models.Index(
                        fields=["patient", "appointment_date_time"],
                        name="appointment_patient_a27322_idx",
                    ),
                    models.Index(
                        fields=["status", "appointment_date_time"],
                        name="appointment_status_431c61_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["SCHEDULED", "CONFIRMED"])),
                        fields=("doctor", "appointment_date_time"),
                        name="unique_doctor_time_appointment",
                    )
                ],
            },
        ),
    ]
