# Generated by Django 5.1.7 on 2025-06-01 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemedicineSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_start_time",
                    models.DateTimeField(
                        db_index=True,
                        verbose_name="Actual or Scheduled Session Start Time",
                    ),
                ),
                (
                    "session_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual Session End Time"
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated duration if scheduled. Actual duration is calculated if end time is set.",
                        null=True,
                        verbose_name="Estimated Duration (minutes)",
                    ),
                ),
                (
                    "session_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the video conference (e.g., Zoom, Google Meet).",
                        max_length=512,
                        null=True,
                        verbose_name="Session URL",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("AWAITING_HOST", "Awaiting Host (Doctor)"),
                            ("AWAITING_GUEST", "Awaiting Guest (Patient)"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Session Status",
                    ),
                ),
                (
                    "reason_for_consultation",
                    models.TextField(
                        blank=True,
                        help_text="Brief reason for the virtual visit. Can be pre-filled from a linked appointment.",
                        verbose_name="Reason for Consultation",
                    ),
                ),
                (
                    "doctor_notes",
                    models.TextField(
                        blank=True, verbose_name="Doctor's Notes (Post-Session)"
                    ),
                ),
                (
                    "patient_feedback",
                    models.TextField(
                        blank=True, verbose_name="Patient Feedback (Post-Session)"
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the session recording, if available and consented.",
                        max_length=512,
                        null=True,
                        verbose_name="Session Recording URL (Optional)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Record Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Record Updated At"
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to a pre-scheduled telemedicine appointment, if any.",
                        limit_choices_to={"appointment_type": "TELEMEDICINE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telemedicine_session_details",
                        to="appointments.appointment",
                        verbose_name="Linked Appointment (Optional)",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_telemedicine_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemedicine_sessions",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telemedicine Session",
                "verbose_name_plural": "Telemedicine Sessions",
                "ordering": ["-session_start_time"],
                "indexes": [
                    models.Index(
                        fields=["patient", "session_start_time"],
                        name="telemedicin_patient_f58017_idx",
                    ),
                    models.Index(
                        fields=["doctor", "session_start_time"],
                        name="telemedicin_doctor__c947fe_idx",
                    ),
                    models.Index(
                        fields=["status", "session_start_time"],
                        name="telemedicin_status_76d091_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "SCHEDULED",
                                    "AWAITING_HOST",
                                    "AWAITING_GUEST",
                                    "IN_PROGRESS",
                                ],
                            )
                        ),
                        fields=("doctor", "session_start_time"),
                        name="unique_doctor_telemedicine_time",
                    )
                ],
            },
        ),
    ]
