# Generated by Django 5.1.7 on 2025-06-01 01:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created Record"),
                            ("UPDATED", "Updated Record"),
                            ("DELETED", "Deleted Record"),
                            ("VIEWED", "Viewed Record"),
                            ("LOGIN_SUCCESS", "Login Successful"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                            ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                            ("USER_REGISTERED", "User Registered"),
                            ("USER_PROFILE_UPDATED", "User Profile Updated by Self"),
                            ("ADMIN_USER_UPDATED", "User Profile Updated by Admin"),
                            ("ADMIN_USER_DELETED", "User Account Deleted by Admin"),
                            ("APPOINTMENT_SCHEDULED", "Appointment Scheduled"),
                            ("APPOINTMENT_UPDATED", "Appointment Updated"),
                            ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                            ("APPOINTMENT_COMPLETED", "Appointment Marked Completed"),
                            ("APPOINTMENT_RESCHEDULED", "Appointment Rescheduled"),
                            ("INVOICE_GENERATED", "Invoice Generated"),
                            ("INVOICE_SENT", "Invoice Sent"),
                            ("INVOICE_UPDATED", "Invoice Updated"),
                            ("INVOICE_VOIDED", "Invoice Voided"),
                            ("PAYMENT_RECORDED", "Payment Recorded"),
                            ("PAYMENT_UPDATED", "Payment Updated"),
                            ("PAYMENT_DELETED", "Payment Deleted"),
                            ("PRESCRIPTION_ISSUED", "Prescription Issued"),
                            ("PRESCRIPTION_UPDATED", "Prescription Updated"),
                            ("PRESCRIPTION_DELETED", "Prescription Deleted"),
                            ("TREATMENT_RECORDED", "Treatment Recorded"),
                            ("TREATMENT_UPDATED", "Treatment Updated"),
                            ("TREATMENT_DELETED", "Treatment Deleted"),
                            ("OBSERVATION_LOGGED", "Observation Logged"),
                            ("OBSERVATION_UPDATED", "Observation Updated"),
                            ("OBSERVATION_DELETED", "Observation Deleted"),
                            ("PATIENT_PROFILE_CREATED", "Patient Profile Created"),
                            ("PATIENT_PROFILE_UPDATED", "Patient Profile Updated"),
                            ("MEDICAL_RECORD_CREATED", "Medical Record Created"),
                            ("MEDICAL_RECORD_UPDATED", "Medical Record Updated"),
                            ("MEDICAL_RECORD_DELETED", "Medical Record Deleted"),
                            ("TELEMED_SESSION_CREATED", "Telemedicine Session Created"),
                            ("TELEMED_SESSION_UPDATED", "Telemedicine Session Updated"),
                            (
                                "TELEMED_SESSION_CANCELLED",
                                "Telemedicine Session Cancelled",
                            ),
                            (
                                "TELEMED_SESSION_COMPLETED",
                                "Telemedicine Session Completed",
                            ),
                            ("TELEMED_SESSION_DELETED", "Telemedicine Session Deleted"),
                            ("INQUIRY_SUBMITTED", "Inquiry Submitted"),
                            ("INQUIRY_UPDATED", "Inquiry Updated"),
                            ("INQUIRY_CLOSED", "Inquiry Closed"),
                            ("INQUIRY_DELETED", "Inquiry Deleted by Admin"),
                            ("ADMIN_ACTION", "Admin General Action"),
                            ("SYSTEM_EVENT", "System Event"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Action Performed",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="A human-readable description of the action and its context.",
                        verbose_name="Details",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="The IP address from which the action was performed.",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="The User-Agent string of the client.",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "target_object_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Target Object ID",
                    ),
                ),
                (
                    "target_object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the target object at the time of logging (e.g., if deleted).",
                        max_length=255,
                        verbose_name="Target Object Representation",
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True,
                        help_text="A JSON field to store any extra structured data related to the audit log entry.",
                        null=True,
                        verbose_name="Additional Information",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Target Model Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the action. Null for system actions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="auditlog_target_idx",
                    ),
                    models.Index(
                        fields=["user", "action"], name="auditlog_user_action_idx"
                    ),
                ],
            },
        ),
    ]
