# Generated by Django 5.1.7 on 2025-06-01 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_report_on_load",
                    models.CharField(
                        blank=True,
                        help_text="Identifier for the default report to load on dashboard access (e.g., 'patient_statistics', 'financial_report').",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "items_per_page_reports",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Default number of items to show per page in report tables within the admin dashboard.",
                    ),
                ),
                (
                    "dashboard_theme",
                    models.CharField(
                        default="default",
                        help_text="Preferred theme for the admin dashboard (e.g., 'default', 'dark', 'light').",
                        max_length=50,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The administrator user associated with these dashboard preferences.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_dashboard_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Dashboard Preference",
                "verbose_name_plural": "Admin Dashboard Preferences",
                "ordering": ["user__username"],
            },
        ),
    ]
