// src/utils/rolePermissions.js
import { USER_ROLES } from './constants';

// Define permissions as constants for better maintainability
export const PERMISSION_KEYS = {
  // Patient Viewing
  VIEW_PATIENT_LIST: 'VIEW_PATIENT_LIST',
  VIEW_PATIENT_PROFILE: 'VIEW_PATIENT_PROFILE', // For viewing the main profile page
  MANAGE_PATIENT_PROFILE_DETAILS: 'MANAGE_PATIENT_PROFILE_DETAILS', // For editing patient's own demographic/contact info (PatientForm.jsx)

  // Medical Records (General clinical notes, diagnoses, etc.)
  VIEW_PATIENT_MEDICAL_RECORDS: 'VIEW_PATIENT_MEDICAL_RECORDS', // General permission to view any medical record tab
  CREATE_MEDICAL_RECORD: 'CREATE_MEDICAL_RECORD',
  MANAGE_MEDICAL_RECORD: 'MANAGE_MEDICAL_RECORD', // Edit/Delete specific records

  // Prescriptions
  VIEW_PRESCRIPTIONS: 'VIEW_PRESCRIPTIONS',
  CREATE_PRESCRIPTION: 'CREATE_PRESCRIPTION',
  MANAGE_PRESCRIPTION: 'MANAGE_PRESCRIPTION',

  // Treatments
  VIEW_TREATMENTS: 'VIEW_TREATMENTS',
  RECORD_TREATMENT: 'RECORD_TREATMENT', // Create
  MANAGE_TREATMENT: 'MANAGE_TREATMENT', // Edit/Delete

  // Observations
  VIEW_OBSERVATIONS: 'VIEW_OBSERVATIONS',
  LOG_OBSERVATION: 'LOG_OBSERVATION', // Create
  MANAGE_OBSERVATION: 'MANAGE_OBSERVATION', // Edit/Delete

  // Appointments
  SCHEDULE_APPOINTMENT_FOR_SELF: 'SCHEDULE_APPOINTMENT_FOR_SELF',
  SCHEDULE_APPOINTMENT_FOR_OTHERS: 'SCHEDULE_APPOINTMENT_FOR_OTHERS',
  VIEW_ALL_APPOINTMENTS: 'VIEW_ALL_APPOINTMENTS', // Staff view of all appointments
  VIEW_OWN_APPOINTMENTS: 'VIEW_OWN_APPOINTMENTS', // Patient/Doctor viewing their own
  MANAGE_ALL_APPOINTMENTS: 'MANAGE_ALL_APPOINTMENTS', // Admin/Receptionist editing status, etc.
  MANAGE_OWN_APPOINTMENTS_DOCTOR: 'MANAGE_OWN_APPOINTMENTS_DOCTOR',
  CANCEL_OWN_APPOINTMENT_PATIENT: 'CANCEL_OWN_APPOINTMENT_PATIENT',

  // Billing & Invoices
  MANAGE_INVOICES: 'MANAGE_INVOICES',
  CREATE_INVOICE: 'CREATE_INVOICE',
  RECORD_PAYMENT: 'RECORD_PAYMENT',
  VIEW_OWN_INVOICES: 'VIEW_OWN_INVOICES',

  // Telemedicine
  MANAGE_TELEMEDICINE_SESSIONS: 'MANAGE_TELEMEDICINE_SESSIONS', // Staff scheduling/managing
  JOIN_TELEMEDICINE_PATIENT: 'JOIN_TELEMEDICINE_PATIENT',
  JOIN_TELEMEDICINE_DOCTOR: 'JOIN_TELEMEDICINE_DOCTOR',
  SUBMIT_TELEMEDICINE_FEEDBACK: 'SUBMIT_TELEMEDICINE_FEEDBACK', // Patient submitting feedback

  // Inquiries
  MANAGE_INQUIRIES_STAFF: 'MANAGE_INQUIRIES_STAFF',
  SUBMIT_INQUIRY: 'SUBMIT_INQUIRY', // For any logged-in user or public

  // Admin Specific
  VIEW_ADMIN_DASHBOARD: 'VIEW_ADMIN_DASHBOARD',
  VIEW_REPORTS: 'VIEW_REPORTS',
  MANAGE_ALL_USERS: 'MANAGE_ALL_USERS', // Full CRUD on users
  ACCESS_SYSTEM_SETTINGS: 'ACCESS_SYSTEM_SETTINGS', // Broader system config if needed
};

const PERMISSIONS = {
  // Patient Viewing & Profile Management
  [PERMISSION_KEYS.VIEW_PATIENT_LIST]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE, USER_ROLES.RECEPTIONIST],
  [PERMISSION_KEYS.VIEW_PATIENT_PROFILE]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE, USER_ROLES.RECEPTIONIST], // Added Admin
  [PERMISSION_KEYS.MANAGE_PATIENT_PROFILE_DETAILS]: [USER_ROLES.ADMIN, USER_ROLES.RECEPTIONIST, USER_ROLES.PATIENT], // Patient can edit their own

  // Medical Records (General clinical notes, diagnoses, etc.)
  [PERMISSION_KEYS.VIEW_PATIENT_MEDICAL_RECORDS]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE], // Added Admin, Receptionist might not need this
  [PERMISSION_KEYS.CREATE_MEDICAL_RECORD]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE],
  [PERMISSION_KEYS.MANAGE_MEDICAL_RECORD]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE],

  // Prescriptions
  [PERMISSION_KEYS.VIEW_PRESCRIPTIONS]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE, USER_ROLES.PATIENT], // Patient views own
  [PERMISSION_KEYS.CREATE_PRESCRIPTION]: [USER_ROLES.DOCTOR], // Typically only doctors
  [PERMISSION_KEYS.MANAGE_PRESCRIPTION]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR], // Edit/delete

  // Treatments
  [PERMISSION_KEYS.VIEW_TREATMENTS]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE, USER_ROLES.PATIENT],
  [PERMISSION_KEYS.RECORD_TREATMENT]: [USER_ROLES.DOCTOR, USER_ROLES.NURSE],
  [PERMISSION_KEYS.MANAGE_TREATMENT]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE],

  // Observations
  [PERMISSION_KEYS.VIEW_OBSERVATIONS]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE, USER_ROLES.PATIENT],
  [PERMISSION_KEYS.LOG_OBSERVATION]: [USER_ROLES.DOCTOR, USER_ROLES.NURSE],
  [PERMISSION_KEYS.MANAGE_OBSERVATION]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE],

  // Appointments
  [PERMISSION_KEYS.SCHEDULE_APPOINTMENT_FOR_SELF]: [USER_ROLES.PATIENT],
  [PERMISSION_KEYS.SCHEDULE_APPOINTMENT_FOR_OTHERS]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE, USER_ROLES.RECEPTIONIST],
  [PERMISSION_KEYS.VIEW_ALL_APPOINTMENTS]: [USER_ROLES.ADMIN, USER_ROLES.DOCTOR, USER_ROLES.NURSE, USER_ROLES.RECEPTIONIST],
  [PERMISSION_KEYS.VIEW_OWN_APPOINTMENTS]: [USER_ROLES.PATIENT, USER_ROLES.DOCTOR, USER_ROLES.NURSE], // Staff can see their own too
  [PERMISSION_KEYS.MANAGE_ALL_APPOINTMENTS]: [USER_ROLES.ADMIN, USER_ROLES.RECEPTIONIST],
  [PERMISSION_KEYS.MANAGE_OWN_APPOINTMENTS_DOCTOR]: [USER_ROLES.DOCTOR],
  [PERMISSION_KEYS.CANCEL_OWN_APPOINTMENT_PATIENT]: [USER_ROLES.PATIENT],

  // Billing & Invoices
  [PERMISSION_KEYS.MANAGE_INVOICES]: [USER_ROLES.ADMIN, USER_ROLES.RECEPTIONIST],
  [PERMISSION_KEYS.CREATE_INVOICE]: [USER_ROLES.ADMIN, USER_ROLES.RECEPTIONIST],
  [PERMISSION_KEYS.RECORD_PAYMENT]: [USER_ROLES.ADMIN, USER_ROLES.RECEPTIONIST],
  [PERMISSION_KEYS.VIEW_OWN_INVOICES]: [USER_ROLES.PATIENT],

  // Telemedicine
  [PERMISSION_KEYS.MANAGE_TELEMEDICINE_SESSIONS]: [USER_ROLES.ADMIN, USER_ROLES.RECEPTIONIST, USER_ROLES.DOCTOR],
  [PERMISSION_KEYS.JOIN_TELEMEDICINE_PATIENT]: [USER_ROLES.PATIENT],
  [PERMISSION_KEYS.JOIN_TELEMEDICINE_DOCTOR]: [USER_ROLES.DOCTOR],
  [PERMISSION_KEYS.SUBMIT_TELEMEDICINE_FEEDBACK]: [USER_ROLES.PATIENT],

  // Inquiries
  [PERMISSION_KEYS.MANAGE_INQUIRIES_STAFF]: [USER_ROLES.ADMIN, USER_ROLES.RECEPTIONIST, USER_ROLES.NURSE],
  [PERMISSION_KEYS.SUBMIT_INQUIRY]: [USER_ROLES.PATIENT, USER_ROLES.ADMIN, USER_ROLES.RECEPTIONIST, USER_ROLES.NURSE, 'PUBLIC'], // 'PUBLIC' for unauthenticated

  // Admin Specific
  [PERMISSION_KEYS.VIEW_ADMIN_DASHBOARD]: [USER_ROLES.ADMIN],
  [PERMISSION_KEYS.VIEW_REPORTS]: [USER_ROLES.ADMIN],
  [PERMISSION_KEYS.MANAGE_ALL_USERS]: [USER_ROLES.ADMIN],
  [PERMISSION_KEYS.ACCESS_SYSTEM_SETTINGS]: [USER_ROLES.ADMIN],
};

export const hasPermission = (userRole, permissionKey) => {
  if (!userRole || !permissionKey) {
    return false;
  }
  const allowedRoles = PERMISSIONS[permissionKey];
  if (!allowedRoles) {
    console.warn(`Permission key "${permissionKey}" is not defined in PERMISSIONS object.`);
    return false;
  }
  return allowedRoles.includes(userRole);
};

export default PERMISSIONS; // Exporting the raw permissions object might be useful for some checks
