# Generated by Django 5.1.7 on 2025-06-01 01:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=255, verbose_name="Subject/Reason for Inquiry"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Detailed Description of Inquiry"),
                ),
                (
                    "inquirer_name",
                    models.CharField(
                        blank=True,
                        help_text="Required if not linked to an existing patient or if inquirer is not the patient.",
                        max_length=255,
                        verbose_name="Inquirer's Full Name",
                    ),
                ),
                (
                    "inquirer_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Inquirer's Email",
                    ),
                ),
                (
                    "inquirer_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Inquirer's Phone Number",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone Call"),
                            ("EMAIL", "Email"),
                            ("WALK_IN", "Walk-In"),
                            ("WEB_PORTAL", "Web Portal Form"),
                            ("CHAT", "Live Chat"),
                            ("REFERRAL", "Referral"),
                            ("OTHER", "Other"),
                        ],
                        default="PHONE",
                        max_length=20,
                        verbose_name="Source of Inquiry",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                            ("PENDING_PATIENT", "Pending Patient Response"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="Inquiry Status",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Details about how the inquiry was resolved or actions taken.",
                        verbose_name="Resolution Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Inquiry Received At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated At"),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member currently handling or who resolved the inquiry.",
                        limit_choices_to={
                            "role__in": ["RECEPTIONIST", "ADMIN", "NURSE"]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_inquiries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Handled By (Staff)",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to an existing patient if the inquiry is from or about them.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries_made",
                        to="patients.patient",
                        verbose_name="Associated Patient (if any)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="inquiries_i_status_38a868_idx",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="inquiries_i_source_34cb79_idx",
                    ),
                    models.Index(
                        fields=["patient", "created_at"],
                        name="inquiries_i_patient_3ffbf9_idx",
                    ),
                    models.Index(
                        fields=["handled_by", "status"],
                        name="inquiries_i_handled_659aee_idx",
                    ),
                ],
            },
        ),
    ]
